### ISSUE TITLE
SecurityException: Auth Failed in phar (Su RaspberryPi - Linux)

### ISSUE THREAD

**Issue by mpaletti** [peppelg/TGUserbot#31]
Su windows funziona, ma ho bisogno di metterlo sul raspberry pi (Quindi su linux) in modo da farlo girare 24/7 ma non funziona ed esce come scritto sotto, poi si chiude. Come posso risolvere? Ho php 8 appena installato, ho riprovato più volte ma niente.

```
API:                  danog\MadelineProto\SecurityException: Auth Failed in phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/MTProtoTools/AuthKeyHandler.php:402
Stack trace:
#0 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/MTProtoTools/AuthKeyHandler.php(593): danog\MadelineProto\MTProto->createAuthKey()
#1 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/MTProtoTools/AuthKeyHandler.php(552): danog\MadelineProto\MTProto->initAuthorizationSocket()
#2 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/MTProto.php(1575): danog\MadelineProto\MTProto->initAuthorization()
#3 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/MTProto.php(622): danog\MadelineProto\MTProto->connectToAllDcs()
#4 [internal function]: danog\MadelineProto\MTProto->__construct_async()
#5 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/Coroutine.php(117): Generator->send()
#6 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/amphp/amp/lib/Internal/Placeholder.php(149): danog\MadelineProto\Coroutine->danog\MadelineProto\{closure}()
#7 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/amphp/amp/lib/Deferred.php(52): Amp\Promise@anonymous->resolve()
#8 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/MTProto/OutgoingMessage.php(209): Amp\Deferred->resolve()
#9 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/amphp/amp/lib/Loop/Driver.php(119): danog\MadelineProto\MTProto\OutgoingMessage->danog\MadelineProto\MTProto\{closure}()
#10 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#11 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#12 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/Tools.php(315): Amp\Loop::run()
#13 phar:///home/pi/shared/TelegramBots/TGUserbot/madeline-80.phar/vendor/danog/madelineproto/src/danog/MadelineProto/API.php(418): danog\MadelineProto\Tools::wait()
#14 phar:///home/pi/shared/TelegramBots/TGUserbot/TGUserbot.phar/TGUserbot.php(186): danog\MadelineProto\API->startAndLoop()
#15 phar:///home/pi/shared/TelegramBots/TGUserbot/TGUserbot.phar/index.php(89): TGUserbot->start()
#16 /home/pi/shared/TelegramBots/TGUserbot/TGUserbot.phar(9): include('...')
#17 {main}
API:                    More than 10 errors in a second and not inited, exiting!
```

![image](https://user-images.githubusercontent.com/59086526/121525467-adce8f80-c9f8-11eb-8455-c2ba0bc81612.png)

**Comment by peppelg** [comment]
se non erro tguserbot ha bisogno di php 7.2
