### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Composer autoloader detected: madeline.php is incompatible with Composer, please require MadelineProto using composer. in madeline.php:8

### ISSUE THREAD

**Issue by ZaneCEO** [peppelg/TGUserbot#34]
Fino al 03 Dicembre 2021 TGUserbot ha sempre funzionato correttamente. Ora non mi funziona più (errore nel titolo), non so perché.

Ho quindi provato a reinstallare, ma l'errore è sempre lo stesso.

Parto da questa situazione:

````
# ls -la
total 552
drwxr-s--- 2 webstackup www-data   4096 Dec 10 10:46 .
drwxr-s--- 4 webstackup www-data   4096 Dec 10 10:36 ..
-rw-r--r-- 1 root       www-data 552213 Dec 10 10:36 TGUserbot.phar
-rw-r----- 1 webstackup www-data   3054 Dec 15  2020 bot.php
````

Lancio `php TGUserbot.phar`. Ottengo l'errore:

````
PHP Fatal error:  Uncaught Exception: Composer autoloader detected: madeline.php is incompatible with Composer, please require MadelineProto using composer. in madeline.php:8
Stack trace:
#0 phar://TGUserbot.phar/TGUserbot.php(23): include()
#1 phar://TGUserbot.phar/index.php(2): require_once('phar:///var/www...')
#2 TGUserbot.phar(9): include('phar:///var/www...')
#3 {main}
  thrown in madeline.php on line 8
````

Ho Ubuntu 20.04 con PHP 7.4.

**Comment by danog** [comment]
Fixato, aggiorna tguserbot!

**Comment by ZaneCEO** [comment]
@danog Fatto! Ti confermo che ora funziona correttamente. Grazie mille!
